### ISSUE TITLE
[Hero] Mausallus Bahram Alternative Spell Scaling

### ISSUE THREAD

**Issue by sceadu37** [Kohan-Citadel/kohangold-KG-#400]
A static discharge creeps along the ground towards the target grounding them in place

Storm Shackle Roots target for 5 seconds. Otherwise identical to cantrip uses storm shield animation as debuff  

Storm's Cage A group stun for 5 seconds.

**Comment by sceadu37** [comment]
Mausallus needs to keep Storm Shield for the entire progression to maintain damage reflect and survivability. This means that Cantrip or any substitute spell will get replaced when she levels up to Restored. I think it would feel bad to give Royalist a CC ability on a Kohan, only to take it away if they keep the han alive (just like Vulgari's pre-patch anti-scaling). Cantrip is really boring, but I think it _should_ be boring; a unique and useful spell will encourage people to not engage with her and defeat the entire concept of her kit.
Additionally, I think we should give her Storm Armor at some point. It's only a +1AV/+1DV/+1Reverse Damage increase over Storm Shield, but given her squishiness compared to other melee kohan, every bit will count as the game progresses.

**Comment by BoNT325** [comment]
https://github.com/Kohan-Citadel/kohangold-KG-/issues/416#issuecomment-2436801939
Mausallus Adjustments
The same except for otherwise mentioned.

Awake
HP increased to 510
av increased to 27 (+5 from storm shield = 32)
Her melee at awake is pretty high risk similar to Roxana's but she lacks the benefits of bless for her company this should make it more rewarding to get her engaged

Cantrip

Enlightened
55 Mana

Restored
Mana 60

Loses Spell Storm Shield
Passive Sprite Storm Shield.
Personal
AV+5 DV+5
15 Reverse Damage.

Lightning Vestments

remove cantrip, this spell is now more of a hindrance than a boon as it takes time she could be striking enemies with vorpal damage or using her high reverse damage value.

Lightning vestment mana cost to mirror Storm Shield.

Ascended

(removed Lightning lash from this version, having talked to bont I think the shields and reverse damage should be the emphasis of maus)
